# Generated by Django 3.1.2 on 2021-02-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210223_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/', null=True, upload_to=''),
        ),
    ]
