# Generated by Django 3.1.2 on 2021-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210224_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='/profile1.png', upload_to=''),
        ),
    ]
