# Generated by Django 3.1.2 on 2021-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210226_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('收藏數量', '收藏數量'), ('全站歌曲數', '全站歌曲數'), ('聆聽次數', '聆聽次數')], max_length=200, null=True),
        ),
    ]
