# Generated by Django 3.1.2 on 2021-03-24 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20210324_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='song_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
        migrations.AddField(
            model_name='album',
            name='expected_song',
            field=models.CharField(choices=[('計畫內歌曲', '計畫內歌曲'), ('可投入計畫內歌曲', '可投入計畫內歌曲')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='image/profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='image/profile1.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
