# Generated by Django 3.1.2 on 2021-04-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', '點播次數'), ('Pending', '尚未聽過'), ('Delivereds', '已聽過')], max_length=200, null=True),
        ),
    ]
