# Generated by Django 3.1.2 on 2021-03-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_auto_20210324_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_player.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
